### ISSUE TITLE
Packet Filter changes do not work

### ISSUE THREAD

**Issue by maof97** [sonertari/UTMFW#12]
Hello,
I like this project and find it really promising (and also underrated), but at the moment I am facing an inconvenience:

I tried to add rules to pass my own host to connect to anything via the WUI Packet Filter -> Editor, but this doesn't seem to work at all.
If I e.g add a "pass from 10.26.0.10" rule at the end it doesn't actually let this IP pass. I know this could be related to some quick rules above, but the same goes for something like: "block to 1.1.1.1" which I could easily confirm using "ping 1.1.1.1" -> connection still possible. The changes are also not written in the /etc/pf.conf file. If I edit the /etc/pf.conf file manually with these entries from above it all works fine. So it seems that any change via the WUI Rule editor does not seem to affect pf...Or did I oversee something? Afaik the "Load and Save" options are just for saving to another conf. file and not necessary to apply new rules right?

Any help would be appreciated 
Greetings

**Comment by sonertari** [comment]
The Editor works on a copy of pf.conf, which you can reload on the Load & Save page. When you are done editing, you should go to the Display & Install page and use the Install button there. Then I think you will see that pf.conf will be updated with your changes (but if there are any errors, it won't save it unless you force it). HTH,

**Comment by maof97** [comment]
It worked, thanks
