### ISSUE TITLE
Snort UTMFW preprocessor on Linux

### ISSUE THREAD

**Issue by primmus** [sonertari/UTMFW#2]
Hi, is it possible to use sslproxy + snort and the UTMFW preprocessor in linux?
Thank you

**Comment by sonertari** [comment]
Although I don't think I have used anything OpenBSD specific in the UTMFW preprocessor, I have just checked `snort-2.9.9.0_utmfw.diff` under `ports/distfiles` again, and couldn't see anything that could be an issue on Linux. Then again, since I have not tried it with Snort running on Linux, I'd like to hear your report on that.

Btw, as I guess you're already aware, you have to use the UTMFW preprocessor, or else Snort cannot determine src and dst addresses of the connection. Hence Snort rules and logs using such information would be broken (they would have 127.0.0.1 for all such addresses).

So, please report back after trying on Linux.

**Comment by primmus** [comment]
It worked perfectly on linux.

Versions used.

 

```
CentOS: Version 7-1
SSLproxy: Version 0.5.6-1
Squid Cache: Version 3.5.26
Snort : Version 2.9.11.1 GRE
```
 



The only change made was in the files sf_preproc_info.h and spp_utmfw.c:

patch_sf_preproc_info.h
```
--- sf_preproc_info.h   2018-06-07 15:19:46.875121324 -0300
+++ /tmp/sf_preproc_info.h      2018-06-05 17:28:01.267331065 -0300
@@ -35,13 +35,12 @@
 #ifndef SF_PREPROC_INFO_H_
 #define SF_PREPROC_INFO_H_

-#define MAJOR_VERSION   1
-#define MINOR_VERSION   0
-#define BUILD_VERSION   1
-#define PREPROC_NAME    "UTMFW_PP"
+extern const int MAJOR_VERSION;
+extern const int MINOR_VERSION;
+extern const int BUILD_VERSION;
+extern const char *PREPROC_NAME;

-#define DYNAMIC_PREPROC_SETUP   UtmfwSetup
-extern void UtmfwSetup();
+extern void DYNAMIC_PREPROC_SETUP(void);

 #endif /* SF_PREPROC_INFO_H_ */
```


 
 
 patch_spp_utmfw.c
```
--- spp_utmfw.c 2018-06-07 15:19:46.875121324 -0300
+++ /tmp/spp_utmfw.c    2018-06-05 17:28:01.266331065 -0300
@@ -65,6 +65,17 @@
 #define DST_PORT_MATCH_STR "utmfw_dpp: dst port match, packet processed for SSLproxy"
 #define MAX_PORTS 10

+const int MAJOR_VERSION = 1;
+const int MINOR_VERSION = 0;
+const int BUILD_VERSION = 1;
+const char *PREPROC_NAME = "UTMFW_PP";
+const char *PROTOCOL_NAME = "UTMFW";
+
+#define UtmfwSetup DYNAMIC_PREPROC_SETUP
+
+
+
+
 typedef struct _UtmfwConfig
 {
     uint16_t portsToListen[MAX_PORTS + 1];
```


thank you

**Comment by sonertari** [comment]
Great, thanks @primmus for reporting back.

Btw a quick question since I don't have a CentOS system, does Snort fail to compile without those changes? Because I didn't have any issues compiling on an Ubuntu 16.04 derivative: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609.

**Comment by primmus** [comment]
It compiles without any problem, but at the time of starting snort it presents the following error and does not initialize:
`
load /usr/local/lib/snort_dynamicpreprocessor//lib_utmfw_dpp.so: /usr/local/lib/snort_dynamicpreprocessor//lib_utmfw_dpp.so: undefined symbol: MAJOR_VERSION
 `
 
```
# dltest /usr/local/lib/snort_dynamicpreprocessor/lib_utmfw_dpp.so
dltest] ERROR dlopen: file not found
```

With these changes the snort loads normally

```
# dltest /usr/local/lib/snort_dynamicpreprocessor/lib_utmfw_dpp.so
SUCCESS: Loaded /usr/local/lib/snort_dynamicpreprocessor/lib_utmfw_dpp.so
```


```
        --== Initialization Complete ==--

   ,,_     -*> Snort! <*-
  o"  )~   Version 2.9.11.1 GRE (Build 268)
   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team
           Copyright (C) 2014-2017 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using libpcap version 1.7.4
           Using PCRE version: 8.32 2012-11-30
           Using ZLIB version: 1.2.7

           Rules Engine: SF_SNORT_DETECTION_ENGINE  Version 3.0  <Build 1>
           Preprocessor Object: SF_MODBUS  Version 1.1  <Build 1>
           Preprocessor Object: SF_IMAP  Version 1.0  <Build 1>
           Preprocessor Object: SF_DNP3  Version 1.1  <Build 1>
           Preprocessor Object: SF_SIP  Version 1.1  <Build 1>
           Preprocessor Object: SF_REPUTATION  Version 1.1  <Build 1>
           Preprocessor Object: SF_POP  Version 1.0  <Build 1>
           Preprocessor Object: SF_FTPTELNET  Version 1.2  <Build 13>
           Preprocessor Object: SF_SDF  Version 1.1  <Build 1>
           Preprocessor Object: UTMFW_PP  Version 1.0  <Build 1>
           Preprocessor Object: SF_SSLPP  Version 1.1  <Build 4>
           Preprocessor Object: SF_SSH  Version 1.1  <Build 3>
           Preprocessor Object: SF_GTP  Version 1.1  <Build 1>
           Preprocessor Object: SF_DCERPC2  Version 1.0  <Build 3>
           Preprocessor Object: SF_SMTP  Version 1.1  <Build 9>
           Preprocessor Object: SF_FILE  Version 1.1  <Build 1>
           Preprocessor Object: SF_DNS  Version 1.1  <Build 4>
           Preprocessor Object: appid  Version 1.1  <Build 5>
```

**Comment by sonertari** [comment]
@primmus, thanks to your feedback and patches I have realized that there are changes to certain preproc definitions in snort 2.9.11.1. So I have updated and cleaned up the Snort UTMFW preprocessor code to comply with the new snort version (you might want to use the new code too). Thanks again for trying on Linux and reporting back.

So I am going to close this issue.
